import { GameInfo } from './game-info';
import { Currency } from './currency.interface';

export interface Building {
    name: string;
    amount: number;
    currencies: Currency[];
    selected: boolean;
    tier: number;
    tierChances: number[];
    tierOptions: number[];
    tierTotalChances: number;
    growthThrowaway: number[];
    growth: number[];
    priceThrowaway: number[];
    curCost: Currency[];
    price: number[];
    priceGrowth: number[];
    row: number;
    col: number;
    minGrowth: number;
    maxGrowth: number;
    minPrice: number;
    maxPrice: number;
    basePrice: number[];
    minPriceGrowth: number;
    maxPriceGrowth: number;
    rerollBasePriceCost: number;
    rerollGrowthCost: number;
    rerollPriceGrowthCost: number;
    rerollTierCost: number;
    canBuy: boolean;
    draw(): void;
    tick(): void;
    build(amount: number): void;
    rerollBasePrice(pos: number): void;
    rerollGrowth(pos: number): void;
    rerollPriceGrowth(pos: number): void;
    rerollCurrency(pos: number, gameInfo: GameInfo): void;
    rerollTier(gameInfo: GameInfo): void;
    select(): void;
    deselect(): void;
    selectTick(): void;
}